language: python
matrix:
  include:
  - os: linux
    dist: jammy
    sudo: true
    python: '3.7'
  - os: linux
    dist: jammy
    sudo: true
    python: '3.8'
  - os: linux
    dist: jammy
    sudo: true
    python: '3.9'
  - os: linux
    dist: jammy
    sudo: true
    python: '3.10'
  - os: linux
    dist: jammy
    sudo: true
    python: '3.11'
cache:
  directories:
    - ~/.cache/pip
install:
  - pip install numpy cython
  - python setup.py install
script:
  - python tests/test_jenks.py
addons:
  apt:
    packages:
      - python3-numpy
