name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: "Build wheels"
        uses: pypa/cibuildwheel@v2.8.1
        with:
          package-dir: python
        env:
          CIBW_BEFORE_BUILD: pip install numpy cython
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.6, <=3.10"
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
          CIBW_SKIP: "*musllinux*"
          CIBW_ARCHS: native
          CIBW_TEST_COMMAND: python {package}/tests/test_jenks.py

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
